services:
  rabbitmq:
    image: "rabbitmq:4-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABIITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: "redis:8.2.1"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  rabbitmq_data: {}
  redis_data: {}

